safe: false
port: 8081
source: site
destination: ./appengine/build/devsite
markdown: kramdown
permalink: /articles/:title.html
fundamentals: /web/fundamentals
baseurl: /web
url: /web
highlighter: pygments
pygments: true
github:
  root: https://github.com/Google/WebFundamentals
  content: tree/master/src/site
include_open_html: false
generate_sample_jshtml: true
spotlights: false
custom:
kramdown:
  toc_levels: "2"
include: ['.htaccess', '_project.yaml', '_book.yaml']
exclude: ['README.md', '*.rb', '*.psd', 'js/*', '*.pxm', 'npm-debug.log']
langs_available: ['ko', 'he']
