# For AppEngine
safe: false
port: 8081
source: site
destination: appengine/build/static
markdown: kramdown
permalink: /articles/:title.html
baseurl: /web
fundamentals: /web/fundamentals
url: /web
highlighter: pygments
pygments: true
spotlights: false
github:
  root: https://github.com/Google/WebFundamentals
  content: tree/master/src/site
include_open_html: true
custom:
kramdown:
  toc_levels: "2"
  entity_output: :as_input
include: ['.htaccess']
exclude: ['config.rb']
# comment this for plain jekyll serve usage.
langs_available: ['de', 'es', 'fr', 'he', 'it', 'ja', 'ko', 'nl', 'pl', 'pt-br', 'ru', 'zh-cn']
sample_link_base: "/web/fundamentals/resources/samples/"
