safe: false
port: 8081
source: site
destination: appengine/build/static
markdown: kramdown
permalink: /articles/:title.html
baseurl: 
fundamentals: /fundamentals
url: 
highlighter: pygments
spotlights: false
github:
  root: https://github.com/Google/WebFundamentals
  content: tree/master/src/site
custom:
kramdown:
  toc_levels: "2"
include: ['.htaccess']
exclude: ['config.rb']
include_open_html: true
sample_link_base: "/fundamentals/resources/samples/"